build_ios_pod.sh
build_macos_pod.sh

Ensure that we have all archs available

[add rustup target]

---

Cargo.toml
DashSharedCore.podspec
build_ios_pod.sh
build_macos_pod.sh
check_rust_version.sh

Just check current rustc version and exit if it's not suitable for build

Add rustc version check

---

DashSharedCore.podspec

[point podspec to version]

---

DashSharedCore.podspec
README.md

[update spec version & readme]

---

Cargo.toml
DashSharedCore.podspec

[0.1.9: fix quorum rotation quarters]

---

Cargo.toml
DashSharedCore.podspec

[0.2.4: log tuning]

---

DashSharedCore.podspec

[update podspec version]

---

Cargo.toml
DashSharedCore.podspec

Link masternode-diff-processor to commit (pre-BLS-basic)

[0.2.8: link to masternode-diff-processor with pre bls-basic version]

---

Cargo.toml

Remove 'branch' as it overrides 'rev'

[remove 'branch']

---

Cargo.toml
build.rs
build_ios_pod.sh
build_macos_pod.sh
cbindgen.toml
check_rust_version.sh

Support for Core v0.19
https://github.com/dashpay/dips/blob/master/dip-0028.md
+ rust BLS
+ a lot of crypto algos

v.0.3.0: Core v0.19 support

---

DashSharedCore.podspec

[updaet podspec]

---

Cargo.toml
DashSharedCore.podspec

0.3.2
Fixes for skipping rotated quorums mechanism

Fix/core v0.19

---

Cargo.toml
DashSharedCore.podspec

0.3.4
Some additional tests for quorums
Change snapshot FFI API

Fix/core v0.19 log

---

.github/workflows/apple_bindings.yml

[fix github flow path]

---

.github/workflows/apple-bindings.yml
.github/workflows/coverage.yml
.github/workflows/masternode-processor.yml
README.md

[add badge]

---

dash-spv-apple-bindings/DashSharedCore.podspec

[revert podspec paths]

---

Cargo.lock
dash-spv-apple-bindings/Cargo.toml
dash-spv-apple-bindings/DashSharedCore.podspec
dash-spv-masternode-processor/src/bindings/masternode.rs
dash-spv-masternode-processor/src/chain/common/chain_type.rs
dash-spv-masternode-processor/src/models/masternode_list.rs
dash-spv-masternode-processor/src/processing/processor.rs

Support hpmn_only for calc platform 25_67 quorums
Add new devnets

feat: Devnet screwdriver

---

Cargo.lock
dash-spv-apple-bindings/Cargo.toml
dash-spv-apple-bindings/DashSharedCore.podspec
dash-spv-masternode-processor/src/chain/common/chain_type.rs

[0.3.8: update devnet configs]

---

dash-spv-apple-bindings/Cargo.toml
dash-spv-apple-bindings/DashSharedCore.podspec
dash-spv-masternode-processor/src/processing/processor.rs

v4.0.0: remove logs as it can take up a lot of space

[v0.4.0: remove logs]

---

Cargo.lock
DashSharedCore.podspec
dash-spv-apple-bindings/Cargo.toml
dash-spv-masternode-processor/Cargo.toml
dash-spv-masternode-processor/src/bindings/keys.rs
dash-spv-masternode-processor/src/crypto/byte_util.rs
dash-spv-masternode-processor/src/keys/dip14.rs
dash-spv-masternode-processor/src/keys/ecdsa_key.rs
dash-spv-masternode-processor/src/keys/ed25519_key.rs
dash-spv-masternode-processor/src/keys/key.rs
dash-spv-masternode-processor/src/tests/keys/ed25519.rs

Fix for ed25519 child key derivation
Update tests

fix: ed-25519 derivation 1-st byte

---

dash-spv-apple-bindings/Cargo.toml
dash-spv-masternode-processor/src/bindings/address.rs

Check script nullability while retrieving an address by script pubkey or signature

fix: Crash while sending tx

---

DashSharedCore.podspec

Fix: Crash while sending tx 
Added nullability check for scripts coming from DashSync

Release 0.4.11

---

dash-spv-apple-bindings/src/coinjoin.rs
dash-spv-coinjoin/src/callbacks.rs
dash-spv-coinjoin/src/wallet_ex.rs

Some code from https://github.com/dashpay/dashsync-iOS/pull/528 requires additional callbacks

feat:(coinjoin): callbacks for availableCoins

---

DashSharedCore.podspec
dash-spv-apple-bindings/Cargo.toml

chore: disable "generate-dashj-tests"
